export type RootStackParamList = {
  Login: undefined;
  Dashboard: undefined;
  Shed: { animalId?: string; mode?: string } | undefined;
  Round: undefined;
  TankDelivery: { milkRoundId: string };
  Conflicts: undefined;
  Inbox: undefined;
  Expenses: { animalId?: string } | undefined;
  Animals: { species?: string } | undefined;
  AnimalNew: { species?: string } | undefined;
  AnimalEdit: { id: string };
  AnimalDetail: { id: string; tab?: string; mode?: string } | undefined;
  AnimalsImport: undefined;
  AnimalsTags: undefined;
  Batches: undefined;
  BatchNew: { kind?: 'LIVESTOCK' | 'POULTRY' | 'FISH' } | undefined;
  BatchDetail: { id: string };
  Groups: undefined;
  Fish: undefined;
  Scan: undefined;
  Health: { animalId?: string; type?: string } | undefined;
  Breeding: { form?: string; animalId?: string } | undefined;
  Production: undefined;
  Feed: { animalId?: string } | undefined;
  Inventory: undefined;
  Revenue: { animalId?: string } | undefined;
  Pnl: undefined;
  Profit: undefined;
  Reports: undefined;
  Admin: { section?: 'members' | 'audit' } | undefined;
  Cohort: undefined;
  DailySheet: undefined;
};
