export const copy = {
  en: {
    appName: 'Shed',
    login: 'Sign in',
    email: 'Email',
    password: 'Password',
    startMilking: 'Start milking',
    remaining: 'Still to do',
    photoGrid: 'Photos',
    typeNumber: 'Type the number',
    save: 'Save',
    confirmSave: 'Save anyway',
    undo: 'Undo last',
    finish: 'Finish round',
    conflicts: 'Sync conflicts',
    acceptServer: 'Use farm copy',
    offline: 'Saved on this phone. Will sync later.',
    usual: 'Usual',
    cannotSell: 'Must not sell this milk',
    torch: 'Torch',
  },
  ne: {
    appName: 'गोठ',
    login: 'साइन इन',
    email: 'इमेल',
    password: 'पासवर्ड',
    startMilking: 'दुहुन सुरु',
    remaining: 'बाँकी',
    photoGrid: 'फोटो',
    typeNumber: 'नम्बर टाइप गर्नुहोस्',
    save: 'सेभ',
    confirmSave: 'भए पनि सेभ',
    undo: 'रद्द',
    finish: 'रौन्ड सकियो',
    conflicts: 'सिंक बाझियो',
    acceptServer: 'फार्मको रेकर्ड राख्नुहोस्',
    offline: 'यो फोनमा सेभ भयो। पछि सिंक हुन्छ।',
    usual: 'सामान्य',
    cannotSell: 'यो दूध बेच्नु हुँदैन',
    torch: 'टर्च',
  },
} as const;

export type Locale = keyof typeof copy;
