import type { ReproStage, Role, Species, TaskPriority, TaskType } from '@farm/contracts';

export type ReminderRuleDef = {
  code: string;
  taskType: TaskType;
  triggerStage?: ReproStage;
  triggerEvent?: string;
  species?: Species[];
  offsetDays?: number;
  offsetHours?: number;
  fireAtHour?: number;
  repeatEveryDays?: number;
  repeatUntilStage?: ReproStage;
  maxRepeats?: number;
  priority: TaskPriority;
  channels: Array<'PUSH' | 'SMS' | 'VOICE'>;
  escalateAfterMinutes?: number;
  escalateToRole?: Role;
  titleEn: string;
  titleNp: string;
  bodyEn?: string;
  bodyNp?: string;
  actionKeys?: string[];
  active?: boolean;
};

const CRITICAL: Pick<ReminderRuleDef, 'escalateAfterMinutes' | 'escalateToRole'> = {
  escalateAfterMinutes: 30,
  escalateToRole: 'MANAGER',
};

/** System defaults. farmId is null. Species-dependent offsets are resolved in the engine. */
export const SYSTEM_REMINDER_RULES: ReminderRuleDef[] = [
  {
    code: 'COLOSTRUM_1',
    taskType: 'COLOSTRUM_FEED',
    triggerEvent: 'CALVING',
    offsetHours: 2,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS', 'VOICE'],
    ...CRITICAL,
    titleEn: 'Colostrum for {shortNo} — feed within 6 hours of birth',
    titleNp: '{shortNo} लाई बिगौती — जन्मको ६ घण्टाभित्र खुवाउनुहोस्',
    actionKeys: ['colostrum'],
  },
  {
    code: 'COLOSTRUM_2',
    taskType: 'COLOSTRUM_FEED',
    triggerEvent: 'COLOSTRUM_1_DONE',
    offsetHours: 6,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS'],
    ...CRITICAL,
    titleEn: 'Second colostrum for {shortNo}',
    titleNp: '{shortNo} को दोस्रो बिगौती',
    actionKeys: ['colostrum'],
  },
  {
    code: 'COLOSTRUM_3',
    taskType: 'COLOSTRUM_FEED',
    triggerEvent: 'COLOSTRUM_2_DONE',
    offsetHours: 8,
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: 'Third colostrum for {shortNo}',
    titleNp: '{shortNo} को तेस्रो बिगौती',
    actionKeys: ['colostrum'],
  },
  {
    code: 'RETAINED_PLACENTA',
    taskType: 'VET_URGENT',
    triggerEvent: 'CALVING',
    offsetHours: 12,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS', 'VOICE'],
    ...CRITICAL,
    titleEn: 'Check {shortNo} — placenta should have expelled by now',
    titleNp: '{shortNo} जाँच — खेर अहिलेसम्म झरिसक्नुपर्छ',
    actionKeys: ['vet'],
  },
  {
    code: 'POSTPARTUM_1',
    taskType: 'POSTPARTUM_CHECK',
    triggerEvent: 'CALVING',
    offsetDays: 7,
    fireAtHour: 8,
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Day-7 post-calving check {shortNo}',
    titleNp: '{shortNo} बियाएको ७ दिन जाँच',
    actionKeys: ['checkup'],
  },
  {
    code: 'POSTPARTUM_2',
    taskType: 'POSTPARTUM_CHECK',
    triggerEvent: 'CALVING',
    offsetDays: 21,
    fireAtHour: 8,
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Day-21 post-calving check {shortNo}',
    titleNp: '{shortNo} बियाएको २१ दिन जाँच',
    actionKeys: ['checkup'],
  },
  {
    code: 'CALF_HIGH_RISK',
    taskType: 'CALF_HEALTH_CHECK',
    triggerEvent: 'COLOSTRUM_LATE',
    offsetDays: 1,
    fireAtHour: 8,
    repeatEveryDays: 1,
    maxRepeats: 21,
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: 'High-risk calf {shortNo} — daily check',
    titleNp: 'जोखिममा बाच्छा {shortNo} — दैनिक जाँच',
    actionKeys: ['checkup'],
  },
  {
    code: 'VWP_ENDING',
    taskType: 'HEAT_WATCH',
    triggerStage: 'VOLUNTARY_WAIT',
    fireAtHour: 8,
    priority: 'LOW',
    channels: ['PUSH'],
    titleEn: '{shortNo} — voluntary wait ends in 3 days. Start watching for heat.',
    titleNp: '{shortNo} — पर्खाइ ३ दिनमा सकिन्छ। गर्मी हेर्न सुरु गर्नुहोस्।',
    actionKeys: ['heat'],
  },
  {
    code: 'HEAT_WATCH_DAILY',
    taskType: 'HEAT_WATCH',
    triggerStage: 'AWAITING_HEAT',
    fireAtHour: 5,
    repeatEveryDays: 1,
    repeatUntilStage: 'AWAITING_HEAT',
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Heat watch {shortNo} this morning',
    titleNp: 'आज बिहान {shortNo} को गर्मी हेर्नुहोस्',
    actionKeys: ['heat', 'not-seen'],
  },
  {
    code: 'HEAT_WATCH_CYCLE',
    taskType: 'HEAT_WATCH',
    triggerEvent: 'HEAT',
    fireAtHour: 5,
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: '{shortNo} should be in heat again in 2 days',
    titleNp: '{shortNo} फेरि २ दिनमा गर्मीमा हुनुपर्छ',
    actionKeys: ['heat'],
  },
  {
    code: 'SILENT_HEAT_BUFFALO',
    taskType: 'SILENT_HEAT_CHECK',
    triggerStage: 'ANESTRUS_SUSPECTED',
    species: ['BUFFALO'],
    fireAtHour: 4,
    repeatEveryDays: 3,
    repeatUntilStage: 'ANESTRUS_SUSPECTED',
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Check {shortNo} between 4 and 7am — buffalo silent heat',
    titleNp: '{shortNo} बिहान ४ देखि ७ बजेसम्म हेर्नुहोस् — मौन गर्मी',
    actionKeys: ['heat', 'not-seen'],
  },
  {
    code: 'SILENT_HEAT_CATTLE',
    taskType: 'SILENT_HEAT_CHECK',
    triggerStage: 'ANESTRUS_SUSPECTED',
    species: ['COW'],
    fireAtHour: 5,
    repeatEveryDays: 3,
    repeatUntilStage: 'ANESTRUS_SUSPECTED',
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Check {shortNo} at dawn — possible silent heat',
    titleNp: '{shortNo} बिहानै हेर्नुहोस् — मौन गर्मी हुन सक्छ',
    actionKeys: ['heat', 'not-seen'],
  },
  {
    code: 'SERVICE_WINDOW_OPEN',
    taskType: 'SERVICE_WINDOW',
    triggerEvent: 'HEAT',
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: 'Breed {shortNo} now — the service window is open',
    titleNp: '{shortNo} लाई अहिले सेवा दिनुहोस् — समय खुल्यो',
    actionKeys: ['service'],
  },
  {
    code: 'SERVICE_WINDOW_CLOSING',
    taskType: 'SERVICE_WINDOW',
    triggerEvent: 'HEAT',
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: 'Service window for {shortNo} closes in 3 hours',
    titleNp: '{shortNo} को सेवा समय ३ घण्टामा बन्द हुन्छ',
    actionKeys: ['service'],
  },
  {
    code: 'SERVICE_WINDOW_MISSED',
    taskType: 'SERVICE_WINDOW',
    triggerEvent: 'HEAT',
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Service window missed for {shortNo} — watch for the next heat',
    titleNp: '{shortNo} को सेवा समय सकियो — अर्को गर्मी हेर्नुहोस्',
    actionKeys: ['heat'],
  },
  {
    code: 'HEAT_RETURN_WATCH',
    taskType: 'HEAT_WATCH',
    triggerEvent: 'SERVICE',
    fireAtHour: 5,
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Heat watch {shortNo} — if she cycles, the service failed',
    titleNp: '{shortNo} गर्मी हेर्नुहोस् — आएमा सेवा असफल',
    actionKeys: ['heat'],
  },
  {
    code: 'PREG_CHECK_DUE',
    taskType: 'PREGNANCY_CHECK',
    triggerEvent: 'SERVICE',
    fireAtHour: 8,
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: 'Pregnancy check {shortNo}',
    titleNp: '{shortNo} को गर्भ जाँच',
    actionKeys: ['pd'],
  },
  {
    code: 'PREG_CHECK_OVERDUE',
    taskType: 'PREGNANCY_CHECK',
    triggerStage: 'PREGNANCY_CHECK_DUE',
    offsetDays: 14,
    fireAtHour: 8,
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: 'Pregnancy check overdue — {shortNo}',
    titleNp: 'गर्भ जाँच ढिलो — {shortNo}',
    actionKeys: ['pd'],
  },
  {
    code: 'PREG_CHECK_UNKNOWN',
    taskType: 'PD_STALLED',
    triggerStage: 'PREGNANCY_CHECK_DUE',
    offsetDays: 45,
    fireAtHour: 8,
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: 'Bred {n} days ago and never checked. She may be carrying — do not breed again until she has been examined.',
    titleNp: '{n} दिनअघि सेवा भएको, जाँच भएको छैन। गर्भवती हुन सक्छ — जाँच नगरी फेरि सेवा नदिनुहोस्।',
    actionKeys: ['pd'],
  },
  {
    code: 'DRY_OFF_DUE',
    taskType: 'DRY_OFF',
    triggerStage: 'PREGNANT_DRYOFF_DUE',
    triggerEvent: 'PREG_CONFIRMED',
    fireAtHour: 8,
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: 'Dry off {shortNo} — confirm she is still pregnant first',
    titleNp: '{shortNo} को दूध बन्द गर्नुहोस् — पहिले गर्भ छ कि पक्का गर्नुहोस्',
    actionKeys: ['dry-off'],
  },
  {
    code: 'DRY_OFF_OVERDUE',
    taskType: 'DRY_OFF',
    triggerEvent: 'PREG_CONFIRMED',
    fireAtHour: 8,
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: '{shortNo} is still milking — dry-off is overdue',
    titleNp: '{shortNo} अझै दूध दिँदैछ — दूध बन्द गर्न ढिलो भयो',
    actionKeys: ['dry-off'],
  },
  {
    code: 'FEED_TRANSITION',
    taskType: 'FEED_TRANSITION',
    triggerEvent: 'PREG_CONFIRMED',
    offsetDays: -21,
    fireAtHour: 8,
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Transition feed for {shortNo} — 21 days to calving',
    titleNp: '{shortNo} को दाना बदल्नुहोस् — बियाउन २१ दिन',
    actionKeys: ['feed'],
  },
  {
    code: 'CALVING_WATCH_7',
    taskType: 'CALVING_WATCH',
    triggerEvent: 'PREG_CONFIRMED',
    offsetDays: -7,
    fireAtHour: 8,
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: '{shortNo} calving in 7 days',
    titleNp: '{shortNo} ७ दिनमा बियाउने',
    actionKeys: ['calving'],
  },
  {
    code: 'CALVING_WATCH_3',
    taskType: 'CALVING_WATCH',
    triggerEvent: 'PREG_CONFIRMED',
    offsetDays: -3,
    fireAtHour: 8,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS'],
    ...CRITICAL,
    titleEn: '{shortNo} calving in 3 days',
    titleNp: '{shortNo} ३ दिनमा बियाउने',
    actionKeys: ['calving'],
  },
  {
    code: 'CALVING_WATCH_1',
    taskType: 'CALVING_WATCH',
    triggerEvent: 'PREG_CONFIRMED',
    offsetDays: -1,
    fireAtHour: 8,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS'],
    ...CRITICAL,
    titleEn: '{shortNo} calving tomorrow',
    titleNp: '{shortNo} भोलि बियाउने',
    actionKeys: ['calving'],
  },
  {
    code: 'CALVING_TODAY',
    taskType: 'CALVING_WATCH',
    triggerEvent: 'PREG_CONFIRMED',
    fireAtHour: 6,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS'],
    ...CRITICAL,
    titleEn: '{shortNo} due to calve today',
    titleNp: '{shortNo} आज बियाउने',
    actionKeys: ['calving'],
  },
  {
    code: 'CALVING_OVERDUE',
    taskType: 'CALVING_WATCH',
    triggerEvent: 'PREG_CONFIRMED',
    offsetDays: 3,
    fireAtHour: 8,
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: '{shortNo} is 3 days past the due date',
    titleNp: '{shortNo} तोकिएको मितिभन्दा ३ दिन ढिलो',
    actionKeys: ['calving'],
  },
  {
    code: 'CALVING_LATE',
    taskType: 'CALVING_WATCH',
    triggerEvent: 'PREG_CONFIRMED',
    fireAtHour: 8,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS', 'VOICE'],
    ...CRITICAL,
    titleEn: '{shortNo} is well past the due date — check for a lost pregnancy or a calving that was not recorded',
    titleNp: '{shortNo} धेरै ढिलो — गर्भ गएको वा बियाएको तर नलेखिएको हुन सक्छ',
    actionKeys: ['calving', 'vet'],
  },
  {
    code: 'ANESTRUS_WATCH',
    taskType: 'SILENT_HEAT_CHECK',
    triggerStage: 'ANESTRUS_SUSPECTED',
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: '{shortNo} has not shown heat — keep watching',
    titleNp: '{shortNo} लाई गर्मी आएको छैन — हेर्दै रहनुहोस्',
    actionKeys: ['heat'],
  },
  {
    code: 'ANESTRUS_MINERAL',
    taskType: 'ANESTRUS_MINERAL',
    triggerStage: 'ANESTRUS_SUSPECTED',
    offsetDays: 30,
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn:
      '{shortNo} has not shown heat for {daysQuiet} days. Try a daily mineral mixture for 3 weeks before calling the vet — about NPR 400, and it often works.',
    titleNp:
      '{shortNo} लाई {daysQuiet} दिन देखि गर्मी आएको छैन। पशु चिकित्सक बोलाउनु अघि ३ हप्ता खनिज मिश्रण दिनुहोस् — करिब रु ४०० पर्छ र प्राय: काम गर्छ।',
    actionKeys: ['mineral', 'enroll'],
  },
  {
    code: 'ANESTRUS_VET',
    taskType: 'ANESTRUS_VET',
    triggerStage: 'ANESTRUS_SUSPECTED',
    offsetDays: 60,
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: '{shortNo} — {daysQuiet} days without heat. Call the vet.',
    titleNp: '{shortNo} — {daysQuiet} दिन गर्मी छैन। पशु चिकित्सक बोलाउनुहोस्।',
    actionKeys: ['vet', 'enroll', 'stop'],
  },
  {
    code: 'ANESTRUS_DECISION',
    taskType: 'ANESTRUS_DECISION',
    triggerStage: 'ANESTRUS_SUSPECTED',
    offsetDays: 90,
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn:
      '{shortNo} has not shown heat for {daysQuiet} days. Delay is costing about NPR {costOfDelay}. Options: CIDR protocol, continue waiting, or sell. None of these is recommended — the number is the advice.',
    titleNp:
      '{shortNo} लाई {daysQuiet} दिन देखि गर्मी आएको छैन। ढिलाइ करिब रु {costOfDelay} पर्छ। विकल्प: सिडर, पर्खिने, वा बेच्ने। कुनै सिफारिस छैन — अंक नै सल्लाह हो।',
    actionKeys: ['cidr', 'wait', 'sell'],
  },
  {
    code: 'REPEAT_BREEDER_FLAG',
    taskType: 'REPEAT_BREEDER',
    triggerEvent: 'SERVICE_3',
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn:
      '{shortNo} is on service {serviceCount}. Check in this order: energy deficit in the ration, uterine infection, AI timing, semen handling. Cumulative AI cost: NPR {aiCost}.',
    titleNp:
      '{shortNo} को {serviceCount} औं सेवा। यो क्रममा हेर्नुहोस्: दानामा उर्जा कमी, पाठेघरको संक्रमण, एआई समय, वीर्य ह्यान्डलिङ। जम्मा एआई खर्च: रु {aiCost}।',
    actionKeys: ['vet', 'wait'],
  },
  {
    code: 'REPEAT_BREEDER_VET',
    taskType: 'REPEAT_BREEDER',
    triggerStage: 'REPEAT_BREEDER',
    offsetDays: 14,
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: '{shortNo} is still open 14 days after the repeat-breeder flag. Call the vet.',
    titleNp: '{shortNo} दोहोरिने प्रजनन चिन्हको १४ दिनपछि पनि खुला छ। पशु चिकित्सक बोलाउनुहोस्।',
    actionKeys: ['vet'],
  },
  {
    code: 'SYNC_INJECTION',
    taskType: 'SYNC_INJECTION',
    triggerEvent: 'PROTOCOL_STEP',
    priority: 'HIGH',
    channels: ['PUSH', 'SMS'],
    titleEn: 'Injection due for {shortNo}',
    titleNp: '{shortNo} को सुई दिनुहोस्',
    actionKeys: ['injection'],
  },
  {
    code: 'SYNC_INJECTION_URGENT',
    taskType: 'SYNC_INJECTION',
    triggerEvent: 'PROTOCOL_STEP_OVERDUE',
    offsetHours: 6,
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS', 'VOICE'],
    ...CRITICAL,
    titleEn: 'Injection for {shortNo} is 6 hours late — the protocol will break if this is missed',
    titleNp: '{shortNo} को सुई ६ घण्टा ढिलो — छुट्यो भने प्रोटोकल रद्द हुन्छ',
    actionKeys: ['injection'],
  },
  {
    code: 'SYNC_AI_DUE',
    taskType: 'SYNC_AI',
    triggerEvent: 'PROTOCOL_AI',
    priority: 'CRITICAL',
    channels: ['PUSH', 'SMS'],
    ...CRITICAL,
    titleEn: 'AI due today for {shortNo}',
    titleNp: '{shortNo} लाई आज एआई दिनुहोस्',
    actionKeys: ['service'],
  },
  {
    code: 'SYNC_BROKEN',
    taskType: 'PROTOCOL_BROKEN',
    triggerEvent: 'PROTOCOL_BROKEN',
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: 'Protocol for {shortNo} is void — a missed injection. Restart, or switch to CIDR.',
    titleNp: '{shortNo} को प्रोटोकल रद्द — सुई छुट्यो। सुरुबाट वा सिडरमा सार्नुहोस्।',
    actionKeys: ['restart', 'cidr'],
  },
  {
    code: 'HEIFER_BREEDING_AGE',
    taskType: 'HEAT_WATCH',
    triggerStage: 'HEIFER_READY',
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: '{shortNo} is old enough to breed',
    titleNp: '{shortNo} प्रजनन उमेर पुग्यो',
    actionKeys: ['heat'],
  },
  {
    code: 'HEIFER_WEIGH',
    taskType: 'CALF_HEALTH_CHECK',
    triggerStage: 'HEIFER_READY',
    repeatEveryDays: 30,
    repeatUntilStage: 'HEIFER_READY',
    priority: 'NORMAL',
    channels: ['PUSH'],
    titleEn: 'Weigh {shortNo} — heifers need a target weight before first service',
    titleNp: '{shortNo} तौलनुहोस् — पहिलो सेवाअघि तौल पुग्नुपर्छ',
    actionKeys: ['weigh'],
  },
  {
    code: 'HEIFER_OVERDUE',
    taskType: 'ANESTRUS_DECISION',
    triggerStage: 'HEIFER_READY',
    offsetDays: 180,
    priority: 'HIGH',
    channels: ['PUSH'],
    titleEn: '{shortNo} has been ready to breed for 180 days. Accumulated rearing cost: NPR {aiCost}.',
    titleNp: '{shortNo} १८० दिनदेखि प्रजनन तयार छ। जम्मा हुर्काइ खर्च: रु {aiCost}।',
    actionKeys: ['service', 'wait', 'sell'],
  },
];

export const REMINDER_RULE_SLOT: Record<string, number> = Object.fromEntries(
  SYSTEM_REMINDER_RULES.map((rule, i) => [rule.code, i + 1]),
);
